routes:
  user-service: http://localhost:8001
  order-service: http://localhost:8002
  test-service: http://localhost:8001

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: 2405
  dbname: apigateway
